name: ConaIsa

# Relevant to events - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
on:
  pull_request:
    types: [ opened, reopened, ready_for_review ]
    paths:
      - 'GNUmakefile'
      - 'Makefile.in'
      - '.github/workflows/ConaIsa.yml'
      - 'configure.ac'
      - '**.c'
      - '**.cpp'
      - '**.el'
      - '**.h'
      - '**.m'
      - '**.m4'
      - '**.sh'
      - '**.texi'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - name: Install dependencies..
        shell: bash
        run: |
          # By default the debian:stable container doesn't have deb-src which we need to invoke 'apt-get build-deps ...'
          printf '%s\n' \
            "deb http://deb.debian.org/debian stable main" \
            "deb-src http://deb.debian.org/debian stable main" \
          > /etc/apt/sources.list
          apt-get update
          # Container 'debian:stable' doesn't have git by default
          apt-get install --yes git
          # Get dependencies needed to build emacs
          apt-get build-dep --yes emacs
      - name: Pulling git directory..
        uses: actions/checkout@v2
      - name: Building..
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"
          make all
      - name: Checking..
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"
          make check
