name: Shell

# Relevant to events - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
on: 
  pull_request:
    types: [ opened, reopened, ready_for_review ]
    paths:
    - '**.sh'

jobs:
  # Linting
  lint:
    runs-on: ubuntu-latest
    container: debian:testing
    steps:
      - name: Installing dependencies..
        run: |
          apt-get update
          apt-get install --yes \
            git \
            shellcheck
      - name: Pulling git dir..
        uses: actions/checkout@v2
      - name: Processing files..
        # Make sure that bash is used
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"

          # Process files
          ## NOTICE: Do not use for loop to avoid pitfall https://mywiki.wooledge.org/BashPitfalls#pf1
          git --git-dir="$GITHUB_WORKSPACE/.git" ls-files -z -- '*.sh' | while IFS= read -rd '' file; do
              printf 'linting shell file %s\n' "$file"
              shellcheck --external-sources --shell=sh "$file"
          done
